version: '3.8'

services:
  traefik:
    image: traefik:v2.8
    command: 
      -- --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/acme.json:rw
      - ./users:/users:ro
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`traefik.${HOSTNAME}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt

      - traefik.http.routers.traefik.middlewares=admin
      - traefik.http.middlewares.admin.basicauth.usersFile=/users
  stable:
    image: gitlab-ext.exxcellent.de:4567/studentenprojekte/virtuelle-fabrik-frontend:stable
    labels:
      - traefik.http.routers.stable.rule=Host(`stable.${HOSTNAME}`) || Host(`${HOSTNAME}`)
      - traefik.http.routers.stable.entrypoints=websecure
      - traefik.http.routers.stable.tls=true
      - traefik.http.routers.stable.tls.certresolver=letsencrypt

  rc:
    image: gitlab-ext.exxcellent.de:4567/studentenprojekte/virtuelle-fabrik-frontend/frontend:0.0.0-RC2
    labels:
      - traefik.http.routers.rc.rule=Host(`rc.${HOSTNAME}`) && !PathPrefix(`/api`)
      - traefik.http.routers.rc.entrypoints=websecure
      - traefik.http.routers.rc.tls=true
      - traefik.http.routers.rc.tls.certresolver=letsencrypt

  rc-backend:
    image: gitlab-ext.exxcellent.de:4567/studentenprojekte/virtuelle-fabrik-frontend/mock-backend:0.0.0-RC2
    volumes:
      - "./work:/work:rw"
    environment:
      BACKEND_DATA_DIR: "/work"
      BACKEND_PATH: "/api"
    labels:
      - traefik.http.routers.rc-backend.rule=Host(`rc.${HOSTNAME}`) && PathPrefix(`/api`)
      - traefik.http.routers.rc-backend.entrypoints=websecure
      - traefik.http.routers.rc-backend.tls=true
      - traefik.http.routers.rc-backend.tls.certresolver=letsencrypt

  latest:
    image: gitlab-ext.exxcellent.de:4567/studentenprojekte/virtuelle-fabrik-frontend/frontend:latest
    labels:
      - traefik.http.routers.latest.rule=Host(`latest.${HOSTNAME}`) && !PathPrefix(`/api`)
      - traefik.http.routers.latest.entrypoints=websecure
      - traefik.http.routers.latest.tls=true
      - traefik.http.routers.latest.tls.certresolver=letsencrypt

  latest-backend:
    image: gitlab-ext.exxcellent.de:4567/studentenprojekte/virtuelle-fabrik-frontend/mock-backend:latest
    volumes:
      - "./work:/work:rw"
    environment:
      BACKEND_DATA_DIR: "/work"
      BACKEND_PATH: "/api"
    labels:
      - traefik.http.routers.latest-backend.rule=Host(`latest.${HOSTNAME}`) && PathPrefix(`/api`)
      - traefik.http.routers.latest-backend.entrypoints=websecure
      - traefik.http.routers.latest-backend.tls=true
      - traefik.http.routers.latest-backend.tls.certresolver=letsencrypt

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/ubuntu/.docker/config.json:/config.json:ro
    environment:
      WATCHTOWER_POLL_INTERVAL: 300
